name: deployment-workflow.yml

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # GitHub Actions Self-hosted Runner

    steps:
      - name: Execute Deployment Script
        run: |
          chmod +x /home/ubuntu/actions-runner/deployment.sh
          
          /home/ubuntu/actions-runner/deployment.sh